create extension if not exists "pg_cron" with schema "pg_catalog";

drop extension if exists "pg_net";

create extension if not exists "pg_net" with schema "public";


  create table "public"."posts" (
    "id" bigint generated by default as identity not null,
    "title" text,
    "image_url" text,
    "created_at_boh" timestamp with time zone default now(),
    "size" text,
    "color" text,
    "quantity" integer,
    "location" text,
    "name" text,
    "image_path" text,
    "in_progress" text,
    "comment" text,
    "repost" boolean not null default false,
    "created_at_foh" timestamp with time zone default now()
      );



  create table "public"."tokens" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "token" text
      );


CREATE UNIQUE INDEX "Tokens_pkey" ON public.tokens USING btree (id);

CREATE UNIQUE INDEX posts_pkey ON public.posts USING btree (id);

alter table "public"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";

alter table "public"."tokens" add constraint "Tokens_pkey" PRIMARY KEY using index "Tokens_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.call_cleanup_image()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  PERFORM
    net.http_post(
      url := 'https://qbbbsznsxhfllwhborju.supabase.co/functions/v1/cleanup-post-image',
      headers := '{"Content-Type":"application/json"}',
      body := json_build_object(
        'image_path', OLD.image_path
      )::text
    );
  RETURN OLD;
END;
$function$
;

grant delete on table "public"."posts" to "anon";

grant insert on table "public"."posts" to "anon";

grant references on table "public"."posts" to "anon";

grant select on table "public"."posts" to "anon";

grant trigger on table "public"."posts" to "anon";

grant truncate on table "public"."posts" to "anon";

grant update on table "public"."posts" to "anon";

grant delete on table "public"."posts" to "authenticated";

grant insert on table "public"."posts" to "authenticated";

grant references on table "public"."posts" to "authenticated";

grant select on table "public"."posts" to "authenticated";

grant trigger on table "public"."posts" to "authenticated";

grant truncate on table "public"."posts" to "authenticated";

grant update on table "public"."posts" to "authenticated";

grant delete on table "public"."posts" to "service_role";

grant insert on table "public"."posts" to "service_role";

grant references on table "public"."posts" to "service_role";

grant select on table "public"."posts" to "service_role";

grant trigger on table "public"."posts" to "service_role";

grant truncate on table "public"."posts" to "service_role";

grant update on table "public"."posts" to "service_role";

grant delete on table "public"."tokens" to "anon";

grant insert on table "public"."tokens" to "anon";

grant references on table "public"."tokens" to "anon";

grant select on table "public"."tokens" to "anon";

grant trigger on table "public"."tokens" to "anon";

grant truncate on table "public"."tokens" to "anon";

grant update on table "public"."tokens" to "anon";

grant delete on table "public"."tokens" to "authenticated";

grant insert on table "public"."tokens" to "authenticated";

grant references on table "public"."tokens" to "authenticated";

grant select on table "public"."tokens" to "authenticated";

grant trigger on table "public"."tokens" to "authenticated";

grant truncate on table "public"."tokens" to "authenticated";

grant update on table "public"."tokens" to "authenticated";

grant delete on table "public"."tokens" to "service_role";

grant insert on table "public"."tokens" to "service_role";

grant references on table "public"."tokens" to "service_role";

grant select on table "public"."tokens" to "service_role";

grant trigger on table "public"."tokens" to "service_role";

grant truncate on table "public"."tokens" to "service_role";

grant update on table "public"."tokens" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."posts"
  as permissive
  for insert
  to anon
with check (true);



  create policy "Enable read access for all users"
  on "public"."posts"
  as permissive
  for select
  to anon
using (true);



  create policy "Allow public delete from uploads bucket"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'uploads'::text));



  create policy "Allow public read access"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'uploads'::text));



  create policy "Allow uploads for all users"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'uploads'::text));



