
  create table "public"."statistics_frequency" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "start_date" date,
    "end_date" date
      );


CREATE UNIQUE INDEX statistics_frequency_pkey ON public.statistics_frequency USING btree (id);

alter table "public"."statistics_frequency" add constraint "statistics_frequency_pkey" PRIMARY KEY using index "statistics_frequency_pkey";

grant delete on table "public"."statistics_frequency" to "anon";

grant insert on table "public"."statistics_frequency" to "anon";

grant references on table "public"."statistics_frequency" to "anon";

grant select on table "public"."statistics_frequency" to "anon";

grant trigger on table "public"."statistics_frequency" to "anon";

grant truncate on table "public"."statistics_frequency" to "anon";

grant update on table "public"."statistics_frequency" to "anon";

grant delete on table "public"."statistics_frequency" to "authenticated";

grant insert on table "public"."statistics_frequency" to "authenticated";

grant references on table "public"."statistics_frequency" to "authenticated";

grant select on table "public"."statistics_frequency" to "authenticated";

grant trigger on table "public"."statistics_frequency" to "authenticated";

grant truncate on table "public"."statistics_frequency" to "authenticated";

grant update on table "public"."statistics_frequency" to "authenticated";

grant delete on table "public"."statistics_frequency" to "service_role";

grant insert on table "public"."statistics_frequency" to "service_role";

grant references on table "public"."statistics_frequency" to "service_role";

grant select on table "public"."statistics_frequency" to "service_role";

grant trigger on table "public"."statistics_frequency" to "service_role";

grant truncate on table "public"."statistics_frequency" to "service_role";

grant update on table "public"."statistics_frequency" to "service_role";


  create policy "Enable insert for all users"
  on "public"."statistics_frequency"
  as permissive
  for insert
  to public
with check (true);



  create policy "Enable read access for all users"
  on "public"."statistics_frequency"
  as permissive
  for select
  to public
using (true);



