
  create table "public"."groups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "completed_at" timestamp with time zone,
    "count" bigint not null,
    "name" text not null,
    "location" text not null
      );


alter table "public"."posts" add column "group" bigint;

CREATE UNIQUE INDEX groups_pkey ON public.groups USING btree (id);

alter table "public"."groups" add constraint "groups_pkey" PRIMARY KEY using index "groups_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.call_cleanup_image()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
  PERFORM
    net.http_post(
      url := 'https://yjzbzkeboginztsuguxe.supabase.co/functions/v1/cleanup-post-image'::text,
      headers := '{"Content-Type":"application/json","Authorization":"Bearer sb_publishable_LDCyZsuJQpcfURXumdCnUA_zm5FQ6R1", "apikey": "sb_publishable_LDCyZsuJQpcfURXumdCnUA_zm5FQ6R1"}'::jsonb,
      body := json_build_object(
        'image_path', OLD.image_path
      )::jsonb
    );
  RETURN OLD;
END;$function$
;

grant delete on table "public"."groups" to "anon";

grant insert on table "public"."groups" to "anon";

grant references on table "public"."groups" to "anon";

grant select on table "public"."groups" to "anon";

grant trigger on table "public"."groups" to "anon";

grant truncate on table "public"."groups" to "anon";

grant update on table "public"."groups" to "anon";

grant delete on table "public"."groups" to "authenticated";

grant insert on table "public"."groups" to "authenticated";

grant references on table "public"."groups" to "authenticated";

grant select on table "public"."groups" to "authenticated";

grant trigger on table "public"."groups" to "authenticated";

grant truncate on table "public"."groups" to "authenticated";

grant update on table "public"."groups" to "authenticated";

grant delete on table "public"."groups" to "service_role";

grant insert on table "public"."groups" to "service_role";

grant references on table "public"."groups" to "service_role";

grant select on table "public"."groups" to "service_role";

grant trigger on table "public"."groups" to "service_role";

grant truncate on table "public"."groups" to "service_role";

grant update on table "public"."groups" to "service_role";


